apiVersion: v1
kind: Service
metadata:
  name: ks-devops-apiserver
  annotations:
    desc: ''
  namespace: kubesphere-devops-system
  labels:
    app: ks-devops-apiserver
spec:
  selector:
    app: ks-devops-apiserver
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
